package com.vibecode.roadmap.application;
import com.vibecode.output.application.OutputAnalyzer; import com.vibecode.output.domain.*; import com.vibecode.output.infrastructure.*; import com.vibecode.project.application.ProjectService; import com.vibecode.roadmap.domain.*; import com.vibecode.roadmap.infrastructure.*; import com.vibecode.task.application.TaskCompletionPolicy; import com.vibecode.task.domain.*; import com.vibecode.task.infrastructure.*; import java.util.*; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
@Service @Transactional public class WorkflowService { private final ProjectService projects; private final RoadmapRecordRepository roadmaps; private final RoadmapPhaseRecordRepository phases; private final WorkflowTaskRepository tasks; private final TaskDependencyRecordRepository deps; private final TaskAcceptanceCriterionRecordRepository criteria; private final TaskEvidenceRepository evidence; private final OutputAnalysisRecordRepository analyses; private final OutputAnalyzer analyzer; private final TaskCompletionPolicy policy;
 public WorkflowService(ProjectService p,RoadmapRecordRepository r,RoadmapPhaseRecordRepository ph,WorkflowTaskRepository t,TaskDependencyRecordRepository d,TaskAcceptanceCriterionRecordRepository c,TaskEvidenceRepository e,OutputAnalysisRecordRepository a,OutputAnalyzer o,TaskCompletionPolicy policy){projects=p;roadmaps=r;phases=ph;tasks=t;deps=d;criteria=c;evidence=e;analyses=a;analyzer=o;this.policy=policy;}
 public RoadmapRecord createRoadmap(UUID project){projects.requireExisting(project);return roadmaps.findByProjectId(project).orElseGet(()->roadmaps.save(new RoadmapRecord(project)));} public Optional<RoadmapRecord> roadmap(UUID p){projects.requireExisting(p);return roadmaps.findByProjectId(p);} public List<RoadmapPhaseRecord> phases(UUID p){return roadmap(p).map(r->phases.findByRoadmapIdOrderByPosition(r.id())).orElse(List.of());}
 public RoadmapPhaseRecord addPhase(UUID p,int pos,String title,String desc){RoadmapRecord r=createRoadmap(p);if(phases.findByRoadmapIdOrderByPosition(r.id()).stream().anyMatch(x->x.position()==pos))throw new IllegalArgumentException("Phase position already exists");return phases.save(new RoadmapPhaseRecord(r.id(),pos,title,desc));}
 public WorkflowTask addTask(UUID p,UUID phase,int pos,String title,String objective,RiskLevel risk){RoadmapPhaseRecord ph=phases.findById(phase).orElseThrow(()->new NoSuchElementException("Phase not found"));if(!ph.roadmapId().equals(createRoadmap(p).id()))throw new IllegalArgumentException("Phase does not belong to project");if(tasks.findByPhaseIdOrderByPosition(phase).stream().anyMatch(x->x.position()==pos))throw new IllegalArgumentException("Task position already exists");WorkflowTask t=tasks.save(new WorkflowTask(p,phase,pos,title,objective,risk));refresh(p);return t;}
 public void dependency(UUID p,UUID task,UUID depends){WorkflowTask t=requireTask(p,task);WorkflowTask d=requireTask(p,depends);if(t.id().equals(d.id()))throw new IllegalArgumentException("A task cannot depend on itself");deps.save(new TaskDependencyRecord(task,depends));refresh(p);}
 public TaskAcceptanceCriterionRecord criterion(UUID p,UUID task,String text,boolean required){requireTask(p,task);return criteria.save(new TaskAcceptanceCriterionRecord(task,text,required));}
 public OutputAnalysisRecord addEvidence(UUID p,UUID task,EvidenceType type,String raw,String source){WorkflowTask t=requireTask(p,task);TaskEvidence ev=evidence.save(new TaskEvidence(p,task,type,raw,source));OutputAnalysisRecord ar=analyses.save(new OutputAnalysisRecord(ev.id(),analyzer.analyze(raw)));if(ar.status()==OutputAnalysisStatus.SUCCESS){criteria.findByTaskId(task).forEach(c->{if(c.required())c.status(CriterionStatus.SATISFIED);});if(policy.canComplete(deps.findByTaskId(task),map(tasks.findByProjectIdOrderByPhaseIdAscPositionAsc(p)),criteria.findByTaskId(task),ar))t.status(WorkflowTaskStatus.COMPLETED);}else if(ar.status()==OutputAnalysisStatus.BLOCKED)t.status(WorkflowTaskStatus.BLOCKED);else if(ar.status()==OutputAnalysisStatus.FAILURE||ar.status()==OutputAnalysisStatus.PARTIAL)t.status(WorkflowTaskStatus.BLOCKED);else t.status(WorkflowTaskStatus.NEEDS_VALIDATION);refresh(p);return ar;}
 public List<TaskEvidence> evidence(UUID p,UUID task){requireTask(p,task);return evidence.findByTaskIdOrderByCreatedAtDesc(task);} public Optional<OutputAnalysisRecord> latest(UUID task){return evidence.findTopByTaskIdOrderByCreatedAtDesc(task).flatMap(x->analyses.findByEvidenceId(x.id()));} public List<WorkflowTask> tasks(UUID p){projects.requireExisting(p);return tasks.findByProjectIdOrderByPhaseIdAscPositionAsc(p);} public List<TaskAcceptanceCriterionRecord> criteria(UUID task){return criteria.findByTaskId(task);} public List<TaskDependencyRecord> deps(UUID task){return deps.findByTaskId(task);} public WorkflowTask requireTask(UUID p,UUID id){WorkflowTask t=tasks.findById(id).orElseThrow(()->new NoSuchElementException("Task not found"));if(!t.projectId().equals(p))throw new IllegalArgumentException("Task does not belong to project");return t;}
 public void refresh(UUID p){List<WorkflowTask> all=tasks(p);Map<UUID,WorkflowTask> map=map(all);for(WorkflowTask t:all){if(t.status()==WorkflowTaskStatus.COMPLETED||t.status()==WorkflowTaskStatus.BLOCKED||t.status()==WorkflowTaskStatus.NEEDS_VALIDATION)continue;boolean ok=deps.findByTaskId(t.id()).stream().allMatch(d->map.get(d.dependencyTaskId()).status()==WorkflowTaskStatus.COMPLETED);t.status(ok?WorkflowTaskStatus.READY:WorkflowTaskStatus.PLANNED);}for(RoadmapPhaseRecord ph:phases(p)){List<WorkflowTask> pts=tasks.findByPhaseIdOrderByPosition(ph.id());if(!pts.isEmpty()&&pts.stream().allMatch(t->t.status()==WorkflowTaskStatus.COMPLETED||t.status()==WorkflowTaskStatus.SKIPPED))ph.status(PhaseStatus.COMPLETED);else if(pts.stream().anyMatch(t->t.status()==WorkflowTaskStatus.BLOCKED))ph.status(PhaseStatus.BLOCKED);else if(pts.stream().anyMatch(t->t.status()==WorkflowTaskStatus.IN_PROGRESS||t.status()==WorkflowTaskStatus.NEEDS_VALIDATION))ph.status(PhaseStatus.IN_PROGRESS);else if(pts.stream().anyMatch(t->t.status()==WorkflowTaskStatus.READY))ph.status(PhaseStatus.READY);}}
 private Map<UUID,WorkflowTask> map(List<WorkflowTask> list){Map<UUID,WorkflowTask> m=new HashMap<>();list.forEach(t->m.put(t.id(),t));return m;}
}
